trigger: none

pool:
  vmImage: ubuntu-latest


jobs:
- job: test
  container: python:3.7-buster
  steps:
  - script: |
      set -x
      curl -Lo viktor-cli 'https://developers.viktor.ai/api/v1/get-cli/?platform=linux&format=binary' && chmod +x viktor-cli
       git branch -a
       git diff --name-status
      ./viktor-cli ci-install
      ./viktor-cli ci-test
    env:
     VIKTOR_DEV: $(VIKTOR_USERNAME)
     VIKTOR_TOKEN: $(VIKTOR_PAT)
