on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/meganadhan/Megatest
        azure-pipeline-name: 'packagemgmt'
        azure-devops-token: aadelkrftqj2lspvczrrswitk4voek67goyl27qx6titoswzc4ua
